name: ci
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt -- --check
      - run: cargo clippy -- --deny warnings
      - run: cargo clippy --no-default-features --features vec-u8,hash-map -- --deny warnings
      - run: cargo clippy --no-default-features --features bytes,hash-map -- --deny warnings
      - run: cargo clippy --no-default-features --features vec-u8,btree-map -- --deny warnings
      - run: cargo clippy --no-default-features --features bytes,btree-map -- --deny warnings
      - run: cargo test
      - run: cargo test --doc # Don't run doctest with non default-features
      - run: cargo test --no-default-features --features vec-u8,hash-map
      - run: cargo test --no-default-features --features bytes,hash-map
      - run: cargo test --no-default-features --features vec-u8,btree-map
      - run: cargo test --no-default-features --features bytes,btree-map
      - run: cargo test --features chrono
      - run: cargo test --features time
